SELECT USER.ID, ORDER.ID FROM USER INNER JOIN ORDER WHERE USER.ID = ORDER.ID

SELECT USER.ID, ORDER.ID FROM USER LEFT JOIN ORDER WHERE USER.ID = ORDER.ID

SELECT USER.ID, ORDER.ID FROM USER RIGHT JOIN ORDER WHERE USER.ID = ORDER.ID

SELECT USER.ID, ORDER.ID FROM USER FULL OUTER JOIN ORDER WHERE USER.ID = ORDER.ID

SELECT E1.USER, E2.ADMIN FROM EMP E1 INNER JOIN EMP E2 WHERE E1.USER = E2.ADMIN;

SELECT ID FROM USER UNION SELECT ID FROM USER2;

SELECT COUNT(ID), COUNTRY FROM USER GROUP BY COUNTRY -- 나라별 유저 아이디 숫자

SELECT COUNT(ID), COUNTRY FROM USER GROUP BY COUNTRY HAVING ID > 5 ORDER BY ID DESC

SELECT COUNT(ID), COUNTRY FROM USER INNER JOIN ORDER GROUP BY COUNTRY HAVING ID > 5 ORDER BY COUNT(ID) > 5 DESC

SELECT SID FROM SUPLIERS WHERE EXISTS (SELECT FROM PRODUCT WHERE PRODUCT.ID = SUPLIERS.ID AND PRICE < 20)

SELECT ID CASE WHEN ID > 30 THEN 'A' ID < 30 THEN 'B' ELSE 'C' END AS RATE FROM USER;